apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: default
  source:
    path: hello/
    repoURL: git@github.com:linuxhatto/hello.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
